### ISSUE TITLE
Use static template tag instead of STATIC_URL

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica-fpr-admin#27]
`STATIC_URL` is a global only available in the dashboard.

**Comment by Hwesta** [comment]
Looks like best-practicies around `STATIC_URL` vs `{% static %}` changed since Django 1.4.  More info is here https://docs.djangoproject.com/en/1.8/howto/static-files/

**Comment by sevein** [comment]
Yes! I added a commit in my i18n branch of the dashboard making that change: https://github.com/artefactual/archivematica/commit/05ea1439fd475e384fb5e5b433d34545cabf5d8b. I'll submit a pull request.

**Comment by sevein** [comment]
Fixed.
