### ISSUE TITLE
Migrations are using loaddata

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica-fpr-admin#38]
Related: https://github.com/artefactual/archivematica/pull/584

**Comment by sevein** [comment]
Related error when running `manage.py migrate`:

```
RemovedInDjango19Warning: initial_data fixtures are deprecated. Use data migrations instead.
```

**Comment by jhsimpson** [comment]
Discovered a bug in the upgrade process between 1.5.1 and 1.6.0 that is caused by using loaddata.  If a user has customized their fpr at all (replacing any fprules for example) there can be integrityErrors on upgrade, as loaddata attempts to overwrite their changes with the new fixture.

**Comment by sevein** [comment]
Replaced by https://github.com/archivematica/Issues/issues/181#issuecomment-425955337.
