### ISSUE TITLE
Stop using django-annoying

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica-fpr-admin#40]
It's more annoying to have too many dependencies.

**Comment by ablwr** [comment]
This seems like it was resolved in #72?

**Comment by sevein** [comment]
Sounds like #72 didn't really make it. I suspect I accidentally pushed to the wrong mirror. I'll fix.

**Comment by sevein** [comment]
Happy that you found this, @ablwr.
That PR brought the linter and the first tests in this project! I totally forgot about it.
Now in qa/1.x via a62404e, a762136, and 333af7b.

Now we can:

    $ flake8 src/
    $ testproject/manage.py test

:tada:

**Comment by ablwr** [comment]
So does that mean we can close #73 as well?
