### ISSUE TITLE
Load requirements.txt from setup.py

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica-fpr-admin#41]
It'd be easier if we had only one place where we define our dependencies rather than two - the latter is prone to errors.

**Comment by jhsimpson** [comment]
To make sure I understand - there will still be a requirements.txt, and in the install_requires section will get populated by reading the requirements.txt file?

**Comment by sevein** [comment]
Yes. Also, `Django` itself shouldn't be listed as a dependency. Django apps import this package instead.

**Comment by sevein** [comment]
Perhaps we should reconsider this.

- https://packaging.python.org/discussions/install-requires-vs-requirements/
- https://stackoverflow.com/a/33685899

**Comment by sevein** [comment]
Replaced by https://github.com/archivematica/Issues/issues/181#issuecomment-425955337.
