### ISSUE TITLE
Problem: disk image formats not getting correct PRONOM ID

### ISSUE THREAD

**Issue by jhsimpson** [artefactual/archivematica-fpr-admin#49]
The FIDO format id command (defined here: https://github.com/artefactual/archivematica-fpr-admin/blob/stable/1.6.x/fpr/migrations/pronom84_idcommands_all.json#L36 ) 

references a file that is installed as part of archivematicaCommon:
https://github.com/artefactual/archivematica/blob/stable/1.6.x/src/archivematicaCommon/lib/externals/fido/archivematica_format_extensions.xml

This lists some custom formats.  It was added to Archivematica in 2014, because there were disk image formats that, at the time, we not listed in the PRONOM registry.

Now with PRONOM v88, all but one of those custom 'archivematica-x-fmt/*' entries have proper PRONOM IDs.

The Fido command should be updated, so that it no longer references this file. The file can be removed from archivematicaCommon.  

The only entry that is still needed is for 'raw disk image' since there is no PRONOM entry for this.  it should be possible to just include the following xml snippet in the fido fpr command directly:

`  <format>
    <puid>archivematica-fmt/4</puid>
    <name>Raw disk image</name>
    <extension>dd</extension>
    <extension>dd.001</extension>
    <extension>001</extension>
  </format>
`

This problem is blocking https://github.com/JiscRDSS/archivematica/issues/13

**Comment by ablwr** [comment]
@sevein Fine to close?

**Comment by sevein** [comment]
I'm not sure @ablwr, is `Raw disk image` already covered by PRONOM?

```
  <format>
    <puid>archivematica-fmt/4</puid>
    <name>Raw disk image</name>
    <extension>dd</extension>
    <extension>dd.001</extension>
    <extension>001</extension>
  </format>
```

Once they're all covered we can proceed to get rid of `archivematica_format_extensions.xml`, i.e. remove the file from the repo and update the command so it does not reference this file.

Related links:
- https://github.com/artefactual/archivematica/commit/7c5173b
- https://projects.artefactual.com/issues/5245
- https://projects.artefactual.com/issues/5892

**Comment by ablwr** [comment]
Ahhh ok, thanks! TBH I just saw the merged PRs linked to this and wondered if it had been done or not. OK this seems worth investigating for sure... disk images are becoming more and more common.

**Comment by sevein** [comment]
Replaced by https://github.com/archivematica/Issues/issues/228.
