### ISSUE TITLE
Problem: FPR error output is unhelpful

### ISSUE THREAD

**Issue by sallain** [artefactual/archivematica-fpr-admin#61]
Occasionally, while editing a format through the Archivematica FPR UI, an error occurs. The error output looks like this:

`(u'U', u'n', u'a', u'b', u'l', u'e', u' ', u't', u'o', u' ', u's', u'a', u'v', u'e', u',', u' ', u'a', u'n', u' ', u'a', u'c', u't', u'i', u'v', u'e', u' ', u'F', u'o', u'r', u'm', u'a', u't', u' ', u'V', u'e', u'r', u's', u'i', u'o', u'n', u' ', u' ', u'w', u'i', u't', u'h', u' ', u't', u'h', u'i', u's', u' ', u'p', u'r', u'o', u'n', u'o', u'm', u' ', u'i', u'd', u' ', u'a', u'l', u'r', u'e', u'a', u'd', u'y', u' ', u'e', u'x', u'i', u's', u't', u's', u'.')`

Needless to say, it's not super helpful.

**Comment by sevein** [comment]
Fixed by #62.

**Comment by jhsimpson** [comment]
I don't know I kind of like that error message

:+1
