### ISSUE TITLE
Problem: this project isn't using tox/flake8/etc

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica-fpr-admin#73]
It's become a standard in the AM team but this project is not using it yet.
For now, see `.travis.yml` to know more about how we're running the tes.
There is also a mention in `DEVELOPMENT.md`.

**Comment by ablwr** [comment]
If we move this back into Archivematica, this problem will go away. :)

**Comment by sevein** [comment]
Fixed by #72!
